### ISSUE TITLE
Forum - Add a Post button not styled correctly

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/tracker#43]
**Describe the bug**
The Add a Post button is not styled correctly (see Justin's Style Guide) — and its on-hover effect will cause seizures.

**URL where bug occurs (if applicable)**
https://courses.gymna.si/courses/GYM/107/staging/discussion/forum

**To Reproduce**
1. visit the forum while enrolled in a full course

**Screenshots**
![output_JuzTTs](https://user-images.githubusercontent.com/1844496/79791609-a0010b00-831b-11ea-820d-c995035a55fe.gif)

**Comment by mbifulco** [comment]
This is a CSS fix - it looks like one of the hover states on this button needs to be overwritten

**Comment by jgagne** [comment]
@mbifulco — A possible solution for this issue, as well as the alignment the Lessons, Syllabus, Forum, and Add a Post Button:

**CSS**

```css
nav.discussion {
 margin: 0 !important;
}

nav.discussion .new-post-btn {
  position: relative;
  font-family: "brandon-grotesque", "Helvetica Neue", Helvetica;
  font-size: 1em;
  color: #fff;
  background-color: #f8971d;
  padding: .75em 1em;
  border: 0;
}
```

**Before**

![gym-forum-add-post-button-before](https://user-images.githubusercontent.com/5142085/80736543-4bf6e300-8ae0-11ea-9c1f-5bfe0aecff20.png)

**After**

![gym-forum-add-post-button-after](https://user-images.githubusercontent.com/5142085/80736581-55804b00-8ae0-11ea-9ba2-05626ce6eec7.png)

**Hover State**

![gym-forum-add-post-button-hover](https://user-images.githubusercontent.com/5142085/80736688-76e13700-8ae0-11ea-8376-7f8e227efbea.png)
***
