### ISSUE TITLE
Collapse list button does not collapse list of Gym Shorts chapters on Lessons page

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/tracker#47]
**Describe the bug**
Collapse list button does not collapse list of Gym Shorts chapters on Lessons page
Browser: Mac OSX El Capitan v10.11 w/ Chrome v50

Steps: 
1. sign in and navigate to the new Gym Shorts Lessons page,
https://courses.gymna.si/courses/GYM/008/staging/courseware/
2. Click on the Collapse arrow next to the Gym Shorts lesson title on the Left side of the page

Expected results: The collapse button collapses the list of chapters

Actual results: The collapse arrow button shows a hover state. However, clicking on it does nothing.

**URL where bug occurs (if applicable)**
https://courses.gymna.si/courses/GYM/008/staging/courseware/

**Screenshot**
![Screen Shot 2016-05-16 at 3 11 27 PM](https://user-images.githubusercontent.com/1844496/79792168-73012800-831c-11ea-8838-5e61e59e26d8.png)

**Comment by jgagne** [comment]
A possible solution, addressing document issue, as well as the alignment of the Bookmarks button that appears above the chapter navigation:

**CSS**

```css
.courseware-bookmarks-button {
  padding-left: 30px;
}

.course-navigation .button-chapter:only-of-type {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
  cursor: text;
}

.course-navigation .button-chapter:only-of-type:focus {
  outline: none;
}

.course-navigation .button-chapter:only-of-type .icon {
  display: none;
}

.course-navigation .button-chapter:only-of-type .group-heading {
  line-height: 1.25 !important;
  letter-spacing: 1px;
  text-transform: uppercase;;
  margin-right: 14px;
}
```

**List/Heading - Before**

![gym-shorts-heading-bookmark-before](https://user-images.githubusercontent.com/5142085/80734346-05ec5000-8add-11ea-8b01-1bf33f80bd1e.png)

**List/Heading - After**

![gym-shorts-heading-bookmark-after](https://user-images.githubusercontent.com/5142085/80734513-451aa100-8add-11ea-93fb-c7409d588cab.png)

**Bookmarks Button Alignment - Before**

![bookmarks-button-alignment-before](https://user-images.githubusercontent.com/5142085/80734632-75623f80-8add-11ea-91c6-02d6003c9422.png)

**Bookmarks Button Alignment - After**

![bookmarks-button-alignment-after](https://user-images.githubusercontent.com/5142085/80734674-8448f200-8add-11ea-8b09-c61cf0a10c50.png)
